update consolez scripts

diff --git a/usr/local/sbin/consfuncs b/usr/local/sbin/consfuncs
--- a/usr/local/sbin/consfuncs
+++ b/usr/local/sbin/consfuncs
@@ -1,22 +1,50 @@
 #!/bin/bash
 #
-# consfuncs - functions common to consolez
+# consfuncs - consolez functions 
 #
 #+--------------------------------------------------------------------------+
 function verboseMsg
-# write a message to stdout when -v|--verbose (2) or -V|--veryverbose (3) are set
-# Args: the message to write
+# write a message to stdout and log file when verbose is 2 or 3 
+# Args: the message 
 #+--------------------------------------------------------------------------+
  {
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  if [ "$verbose" = 2 ]; then              # verbose
-    echo -e "$@"
-  elif [ "$verbose" = 3 ]; then            # very verbose
-   echo -e "spoolcons: ${FUNCNAME[1]}: $@"
+  if [ "$verbose" -gt 1 ]; then            # verbose or very verbose
+    local timeStamp=`date +"%Y-%m-%d %H:%M:%S,%3N"`
+    echo -e "$timeStamp $0/${FUNCNAME[1]}() user $USER: $@" | tee -a $logFile
   fi
  }                                         # verboseMsg()
+
+#+--------------------------------------------------------------------------+
+function readConfFile
+# Read configuration file /etc/zlma.conf
+# Also set thisUserID and thisSysID - user ID and system ID we are on
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  if [ ! -f $confFile ]; then              # error
+    echo "ERROR: configuration file $confFile not found"
+    exit 1
+  fi
+  local confFileData=`cat $confFile`
+  lpars=`echo "$confFileData" | jq -r '.eng_srvrs[].lpar' | xargs`        # read engineering servers with jq
+  engSrvrs=`echo "$confFileData" | jq -r '.eng_srvrs[].eng_srvr' | xargs` # read LPARs with jq
+  lpars=($lpars)                           # convert to array
+  engSrvrs=($engSrvrs)                     # convert to array
+  numLPARs="${#lpars[@]}"
+  local logLevel=`echo "$confFileData" | grep log_level | awk '{print $2}'`
+  if [ "$logLevel" = '"debug"' ]; then     # in debug mode
+    echo "$cmdCalled: logLevel = debug: increasing verbosity"
+    verbose=2                              # increase verbosity
+  fi
+  local sysinfo=`cat /proc/sysinfo`        # get sysinfo in memory
+  thisUserID=`echo "$sysinfo" | grep "VM00 Name:" | awk '{print $3}'` # user ID of this server
+  thisSysID=`echo "$sysinfo" | grep "LPAR Name:" /proc/sysinfo | awk '{print $3}'` # system ID (LPAR) 
+ }                                         # readConfFile()
 
 #+--------------------------------------------------------------------------+
 function CPcmd
@@ -59,10 +87,7 @@ function CPcmd
 function getEngServer
 # Given a z/VM system ID, return the engineering server
 # Arg 1: LPAR being queried
-# Global variables: 
-#   engServer - the engineering server
-#   tgtCEC    - the CEC
-#   consFile  - saved console file path
+# Return: engineering server host name
 #+--------------------------------------------------------------------------+
  {
   : SOURCE: ${BASH_SOURCE}
@@ -75,8 +100,8 @@ function getEngServer
   fi
 
   # Assign LPARs and engineering servers to arrays
-  lpars=`jq -r '.eng_srvrs[].lpar' /etc/zlma.conf | xargs`         # read engineering servers with jq
-  eng_srvrs=`jq -r '.eng_srvrs[].eng_srvr' /etc/zlma.conf | xargs` # read LPARs with jq
+  lpars=`jq -r '.eng_srvrs[].lpar' $confFile | xargs`         # read engineering servers with jq
+  eng_srvrs=`jq -r '.eng_srvrs[].eng_srvr' $confFile | xargs` # read LPARs with jq
   lpars=($lpars)                           # convert to array
   eng_srvrs=($eng_srvrs)                   # convert to array
   numLPARs="${#lpars[@]}"
diff --git a/usr/local/sbin/cpcommand b/usr/local/sbin/cpcommand
--- a/usr/local/sbin/cpcommand
+++ b/usr/local/sbin/cpcommand
@@ -1,8 +1,4 @@
 #!/bin/bash
-#
-# This code is shipped under the Artistic License 2.0. See the file
-# Artistic-License-2.0.txt or http://opensource.org/licenses/Artistic-2.0
-#
 #+--------------------------------------------------------------------------+
 #
 # cpcommand - issue a CP command on a specified z/VM LPAR 
@@ -18,12 +14,13 @@ function usage
 
   echo ""                                  # leave some room
   echo "Name:   cpcommand - issue a CP command on a specified z/VM LPAR"
-  echo "Usage:  cpcommand [OPTIONS] SYSTEM-ID CP-COMMAND"
+  echo "Usage:  cpcommand [OPTIONS] CP-COMMAND"
   echo "Where:  SYSTEM-ID  is the z/VM system to run the CP command on"
   echo "Where:  CP-COMMAND is CP command to invoke"
   echo ""
   echo "OPTIONS:"
   echo "  -h|--help             Give help"
+  echo "  -l|--lpar [LPAR]      LPAR system identifier to run command on (default: this LPAR)"
   echo "  -s|--silent           Minimal output"
   echo "  -v|--verbose          Include additional output"
   echo "  -V|--veryverbose      Include even more output"
@@ -45,6 +42,15 @@ function parseArgs
     case $1 in
       -h|--help)
         usage
+        ;;
+      -l|--lpar)
+        shift
+        if [ $# = 0 ]; then                # no more args
+          echo "ERROR: not enough arguments"
+          usage
+        fi
+        tgtSysID=`echo $1 | tr [:lower:] [:upper:]` # fold to upper case
+echo "tgtSysID = $tgtSysID"
         ;;
       -s|--silent)
         verbose=0
@@ -70,16 +76,20 @@ function parseArgs
           echo "ERROR: unrecognized flag $1"
           usage 
         fi
-        if [ ${#systemID} = 0 ]; then      # first arg 
-          systemID=`echo $1 | tr [:lower:] [:upper:]` # fold to upper case
-        else                               # second arg
-          cpCmd="$@"                       # all remaining args are the CP command 
-          break;                           # out of while loop
-        fi
+        cpCmd="$@"                         # all remaining args = CP command 
+        break;                             # out of while loop
         ;;
     esac
     shift
   done
+  if [ ${#cpCmd} = 0 ]; then
+    echo "ERROR: CP-COMMAND not specified"
+    usage
+  fi
+  echo "verbose = $verbose"
+  readConfFile
+  echo "AFTER: verbose = $verbose"
+  echo "cpCmd = $cpCmd logLevel = $logLevel"
  }                                         # parseArgs()
 
 #+--------------------------------------------------------------------------+
@@ -114,29 +124,39 @@ function sendCPcommand
   local engServer 
   local rc                                 # a return code
 
-  verboseMsg "trying to get engineering server with: getEngServer $systemID"
-  getEngServer $systemID
-  if [ $? != 0 ]; then 
-    echo "ERROR: did not find LPAR $systemID in $confFile"
-    exit 1                               # object not found
+  if [ ${#tgtSysID} = 0 ]; then            # target LPAR not specified
+    cmd="sudo vmcp $cpCmd"                 # run locally
+  else
+    verboseMsg "trying to get engineering server with: getEngServer $tgtSysID"
+    local engServer
+    engServer=`getEngServer $tgtSysID`
+    if [ $? != 0 ]; then 
+      echo "ERROR: did not find LPAR $tgtSysID in $confFile" | tee -a $logFile
+      exit 1                               # object not found
+    fi
+    cmd="$sshCmd $engServer sudo vmcp $cpCmd" # run remotely
   fi
-
-  # send the CP command
-  cmd="$sshCmd $engServer sudo vmcp $cpCmd"
-  if [ $verbose -ge 1 ]; then              # issue message unless in silent mode
-    echo "Executing CP command with: $cmd"
+  verboseMsg "Executing CP command: $cmd"
+  eval $cmd                                # run command locally or remotely
+  rc=$?
+  if [ "$rc" != 0 ]; then                  # error
+    verboseMsg "WARNING: command: $cmd returned $rc" 
   fi
-  eval $cmd                                # run the command
  }                                         # sendCPcommand()
 
 #+--------------------------------------------------------------------------+
 # Global variables
 declare -A arr                             # array of environments/eng'g servers/LPARs/
 cmdCalled=`basename $0`                    # get the name of the script called
-confFile="/etc/consolez.conf"              # configuration file that must exist            
+confFile="/etc/zlma.conf"                  # configuration file
 cpCmd=""                                   # the CP command to execute
 flags=""                                   # flags to pass on to remote calls
-systemID=""                                # target z/VM LPAR
+logFile="/var/log/zlma/consolez.log"       # log file 
+logLevel="info"                            # log level
+tgtSysID=""                                # target z/VM LPAR
+tgtUserID=""                               # target user ID 
+thisSysID=""                               # this z/VM LPAR
+thisUserID=""                              # this user ID 
 verb=""                                    # operation being performed
 verbose="1"                                # default verbosity level
 vmcpCmd="sudo vmcp --buffer=1M"            # command to issue "vmcp"
@@ -146,6 +166,5 @@ webUI="no"                                 # called from the Web UI?
 source /usr/local/sbin/consfuncs           # import common functions
 parseArgs $@                               # parse arguments
 checkEnv                                   # verify environment
-readConfFile                               # read the /etc/consolez.conf file
 sendCPcommand                              # issue requested CP command
 
